name: Deploy to Vercel

on:
  push:
    branches:
      - main  # ou a branch que quiser usar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # ou a versão do seu projeto

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token da Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # ID da organização
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # ID do projeto
          working-directory: ./
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
